import autogen
import argparse
import os
import chromadb
from datetime import datetime

# ==============================================================================
# 1. Configuration & Argument Parsing
# ==============================================================================
parser = argparse.ArgumentParser(description="AI-Powered FDE Orchestrator")
parser.add_argument("input_file", help="Path to the raw Markdown meeting notes (e.g., ~/Obsidian/meeting.md)")
args = parser.parse_args()

# Determine Output Files
input_path = os.path.abspath(args.input_file)
base_name = os.path.splitext(os.path.basename(input_path))[0]
output_dir = os.path.dirname(input_path)
output_plan_file = os.path.join(output_dir, f"{base_name}_FDE_Plan.md")
knowledge_base_file = os.path.join(output_dir, "fde_knowledge_base.md")

# Load LLM Config
config_list = [
    {
        "model": "gpt-4",
        "api_key": os.environ.get("OPENAI_API_KEY", "YOUR_API_KEY_HERE")
    }
]

llm_config = {
    "config_list": config_list,
    "temperature": 0.1, # Deterministic outputs
}

# ==============================================================================
# 2. Hybrid Memory System (ChromaDB + Markdown)
# ==============================================================================
print("Initializing ChromaDB Semantic Memory...")
db_client = chromadb.PersistentClient(path="./chroma_fde_memory")
collection = db_client.get_or_create_collection(name="fde_rules")

def sync_vectordb_to_markdown():
    """Extracts all learned rules from ChromaDB and writes them to a visible Markdown file."""
    try:
        rules = collection.get()
        if rules and rules['documents']:
            with open(knowledge_base_file, 'w') as f:
                f.write("# FDE AI Knowledge Base & Learned Rules\n\n")
                f.write("> *This file is auto-generated by the FDE Orchestrator's semantic memory. It allows human review of what the AI has learned.*\n\n")
                for doc in rules['documents']:
                    f.write(f"- {doc}\n")
    except Exception as e:
        print(f"Failed to sync VectorDB: {e}")

# Read existing rules to inject into the PM and Architect prompts
existing_rules_prompt = ""
try:
    existing_rules = collection.get()
    if existing_rules and existing_rules['documents']:
        existing_rules_prompt = "\n\nCRITICAL KNOWLEDGE BASE RULES TO FOLLOW:\n" + "\n".join([f"- {r}" for r in existing_rules['documents']])
except Exception:
    pass

# ==============================================================================
# 3. Define the Agents (Human-in-the-Loop enabled)
# ==============================================================================

# User Proxy (You). Configured to PAUSE and ask for your feedback before the Ticket Agent runs.
user_proxy = autogen.UserProxyAgent(
    name="User_Proxy",
    system_message="A human FDE admin. You provide notes and approve the architecture before tickets are made.",
    human_input_mode="TERMINATE", # Pauses execution and asks for human input/approval
    max_consecutive_auto_reply=1,
    code_execution_config=False,
)

discovery_agent = autogen.AssistantAgent(
    name="Discovery_Agent",
    system_message=(
        "You are an expert Forward Deployed Product Manager. "
        "Take raw, messy meeting notes and extract the core business problem, "
        "user needs, and a structured list of desired features. Output a clear 'Product Spec'."
        + existing_rules_prompt
    ),
    llm_config=llm_config,
)

architect_agent = autogen.AssistantAgent(
    name="Architect_Agent",
    system_message=(
        "You are a Senior Systems Architect. You review Product Specs provided by the Discovery_Agent. "
        "Stress-test the architecture for edge cases, database choices, and infrastructure (Docker/K8s). "
        "Output technical constraints that must be added to the tickets."
        + existing_rules_prompt
    ),
    llm_config=llm_config,
)

ticket_agent = autogen.AssistantAgent(
    name="Ticket_Agent",
    system_message=(
        "You are an Agile Delivery Manager. You take the Product Spec and the Architect's constraints, "
        "and break them down into Linear tickets. "
        "Call the 'create_linear_ticket' tool for each ticket you identify."
    ),
    llm_config=llm_config,
)

# ==============================================================================
# 4. Custom Tool: Linear Ticket Creation with Local Fallback
# ==============================================================================
def create_linear_ticket(title: str, description: str):
    """
    Simulates calling the Linear GraphQL API.
    If the API fails or is unavailable, triggers a fallback to append the ticket to the local Markdown plan.
    """
    print(f"\n[Tool Execution] Attempting to create Linear Ticket: {title}")
    
    # Simulate API Failure / Environment missing
    if not os.environ.get("LINEAR_API_KEY"):
        print("[Fallback Triggered] LINEAR_API_KEY not found. Appending ticket to local FDE Plan file instead.")
        with open(output_plan_file, "a") as f:
            f.write(f"\n### LINEAR TICKET: {title}\n")
            f.write(f"{description}\n")
            f.write("---\n")
        return f"Success (Fallback): Ticket '{title}' saved locally to {output_plan_file}."
    
    return f"Success: Ticket '{title}' created in Linear."

# Register tool to the LLM agent
autogen.agentchat.register_function(
    create_linear_ticket,
    caller=ticket_agent,
    executor=user_proxy,
    name="create_linear_ticket",
    description="Creates a ticket in Linear. Call this for every ticket identified."
)

# ==============================================================================
# 5. Run the Workflow!
# ==============================================================================
if __name__ == "__main__":
    print(f"🚀 Initiating FDE AutoGen Workflow for: {input_path}\n")
    
    # Read the input file
    try:
        with open(input_path, 'r') as f:
            raw_meeting_notes = f.read()
    except FileNotFoundError:
        print(f"Error: Could not find file {input_path}")
        exit(1)

    # Prepare output file
    with open(output_plan_file, "w") as f:
        f.write(f"# FDE Workflow Plan: {base_name}\n\n")

    groupchat = autogen.GroupChat(
        agents=[user_proxy, discovery_agent, architect_agent, ticket_agent],
        messages=[],
        max_round=6,
        speaker_selection_method="round_robin"
    )

    manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

    # Start Chat
    user_proxy.initiate_chat(
        manager,
        message=f"Please process these raw notes into a spec, stress-test the architecture, and generate Linear tickets.\n\nNOTES:\n{raw_meeting_notes}"
    )

    # Sync VectorDB to Markdown at the end of the run
    sync_vectordb_to_markdown()
    
    print(f"\n✅ FDE Workflow Complete! View your plan here: {output_plan_file}")
