import autogen
import argparse
import os
import chromadb
from datetime import datetime
import agentops
from typing import Annotated

# ==============================================================================
# 1. Configuration & Argument Parsing
# ==============================================================================
parser = argparse.ArgumentParser(description="AI-Powered FDE Orchestrator")
parser.add_argument("input_file", help="Path to the raw Markdown meeting notes (e.g., ~/Obsidian/meeting.md)")
parser.add_argument("--interactive", action="store_true", help="Enable terminal interaction for approval before ticketing")
args = parser.parse_args()

# Initialize AgentOps for LLM Observability
agentops.init(api_key=os.environ.get("AGENTOPS_API_KEY", "optional-fallback-key"))

# Determine Output Files
input_path = os.path.abspath(args.input_file)
base_name = os.path.splitext(os.path.basename(input_path))[0]
output_dir = os.path.dirname(input_path)
output_plan_file = os.path.join(output_dir, f"{base_name}_FDE_Plan.md")
knowledge_base_file = os.path.join(output_dir, "fde_knowledge_base.md")

# Load LLM Config
config_list = [
    {
        "model": os.environ.get("VERTEX_MODEL_NAME", "gemini-3.1-pro-preview"),
        "api_type": "google",
        "project": os.environ.get("GOOGLE_VERTEX_PROJECT", "extreme-karma-gm"),
        "location": os.environ.get("GOOGLE_VERTEX_LOCATION", "global")
    }
]

llm_config = {
    "config_list": config_list,
    "temperature": 0.1,
    "max_tokens": 8000,
    "request_timeout": 300,
}

# Read the input file first so we can use it for RAG
try:
    with open(input_path, 'r') as f:
        raw_meeting_notes = f.read()
except FileNotFoundError:
    print(f"Error: Could not find file {input_path}")
    exit(1)

# ==============================================================================
# 2. Optimized RAG Semantic Memory (Phase 3)
# ==============================================================================
print("Initializing ChromaDB Semantic Memory...")
db_client = chromadb.PersistentClient(path="./chroma_fde_memory")
collection = db_client.get_or_create_collection(name="fde_rules")

def sync_vectordb_to_markdown():
    """Extracts all learned rules from ChromaDB and writes them to a visible Markdown file."""
    try:
        rules = collection.get()
        if rules and rules['documents']:
            with open(knowledge_base_file, 'w') as f:
                f.write("# FDE AI Knowledge Base & Learned Rules\n\n")
                f.write("> *This file is auto-generated by the FDE Orchestrator's semantic memory.*\n\n")
                for doc in rules['documents']:
                    f.write(f"- {doc}\n")
    except Exception as e:
        print(f"Failed to sync VectorDB: {e}")

existing_rules_prompt = ""
try:
    if collection.count() > 0:
        print("Querying ChromaDB for relevant rules...")
        # Only retrieve the top 3 most relevant rules to this specific meeting
        results = collection.query(query_texts=[raw_meeting_notes], n_results=min(3, collection.count()))
        if results and results['documents'] and results['documents'][0]:
            relevant_rules = results['documents'][0]
            existing_rules_prompt = "\n\nCRITICAL KNOWLEDGE BASE RULES TO FOLLOW:\n" + "\n".join([f"- {r}" for r in relevant_rules])
except Exception as e:
    print(f"Warning: RAG query failed: {e}")

# ==============================================================================
# 3. Define the Agents (Phase 1: Dynamic Collaboration)
# ==============================================================================

# User Proxy (You)
human_mode = "TERMINATE" if args.interactive else "NEVER"
user_proxy = autogen.UserProxyAgent(
    name="User_Proxy",
    system_message="A human FDE admin.",
    human_input_mode=human_mode,
    max_consecutive_auto_reply=0,
    code_execution_config=False,
    is_termination_msg=lambda x: "TERMINATE" in str(x.get("content", "")).upper()
)

enrichment_agent = autogen.AssistantAgent(
    name="Enrichment_Agent",
    system_message=(
        "You are an expert FDE Note Taker. Expand raw notes into a comprehensive, professional meeting overview. "
        "Output ONLY the comprehensive markdown overview."
    ),
    llm_config=llm_config,
)

discovery_agent = autogen.AssistantAgent(
    name="Discovery_Agent",
    system_message=(
        "You are an expert Forward Deployed Product Manager. "
        "Process the meeting overview into a structured 'Product Spec'. "
        "If the Architect_Agent rejects your spec, you must rewrite it addressing their concerns."
        + existing_rules_prompt
    ),
    llm_config=llm_config,
)

architect_agent = autogen.AssistantAgent(
    name="Architect_Agent",
    system_message=(
        "You are a Senior Systems Architect. Review Product Specs from the Discovery_Agent. "
        "Stress-test the architecture. "
        "If there are major flaws, explain them and DO NOT approve. "
        "If the spec is solid, output technical constraints and MUST end your message with the exact phrase: 'ARCHITECTURE APPROVED'. "
        + existing_rules_prompt
    ),
    llm_config=llm_config,
)

ticket_agent = autogen.AssistantAgent(
    name="Ticket_Agent",
    system_message=(
        "You are a Senior Agile Delivery Manager. "
        "When you receive an approved Product Spec and Architect constraints, break them down into tickets. "
        "You MUST use the `create_linear_ticket` tool to generate each ticket. "
        "Do not output raw markdown tickets anymore. Use the tool. "
        "When you are finished creating all tickets, reply with 'TERMINATE'."
    ),
    llm_config=llm_config,
)

# ==============================================================================
# 4. Native Tool Calling (Phase 2)
# ==============================================================================
@user_proxy.register_for_execution()
@ticket_agent.register_for_llm(name="create_linear_ticket", description="Creates a ticket in Linear or local markdown")
def create_linear_ticket(
    title: Annotated[str, "The title of the ticket"],
    description: Annotated[str, "The full markdown description, user story, and acceptance criteria"]
) -> str:
    """Creates a ticket natively using function calling."""
    print(f"\n[Tool Execution] Creating Linear Ticket: {title}")
    
    # Save to the local FDE Plan file
    with open(output_plan_file, "a") as f:
        f.write(f"\n### LINEAR TICKET: {title}\n")
        f.write(f"{description}\n")
        f.write("---\n")
        
    return f"Success: Ticket '{title}' saved locally to {output_plan_file}."

# ==============================================================================
# 5. GroupChat Graph & Orchestration
# ==============================================================================
def state_transition(last_speaker, groupchat):
    messages = groupchat.messages
    
    if last_speaker == user_proxy:
        # User submits raw notes -> enrich them
        return enrichment_agent
    
    if last_speaker == enrichment_agent:
        # Enriched notes -> create product spec
        return discovery_agent
    
    if last_speaker == discovery_agent:
        # Spec -> architect review
        return architect_agent
    
    if last_speaker == architect_agent:
        last_msg = str(messages[-1].get("content", "")).upper()
        if "ARCHITECTURE APPROVED" in last_msg:
            # If interactive mode is on, we let the user proxy approve before ticketing
            if args.interactive:
                return user_proxy
            return ticket_agent
        else:
            # Architect rejected it -> send back to PM
            return discovery_agent
            
    if last_speaker == ticket_agent:
        return None # End chat

groupchat = autogen.GroupChat(
    agents=[user_proxy, enrichment_agent, discovery_agent, architect_agent, ticket_agent],
    messages=[],
    max_round=15,
    speaker_selection_method=state_transition
)

manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

if __name__ == "__main__":
    print(f"🚀 Initiating FDE GroupChat Pipeline for: {input_path}\n")
    
    # Prepare output file
    with open(output_plan_file, "w") as f:
        f.write(f"# FDE Workflow Plan: {base_name}\n\n")
        f.write("## Generated Linear Tickets\n\n")

    # Start the dynamic chat
    user_proxy.initiate_chat(
        manager,
        message=f"Here are the raw meeting notes. Please enrich them, draft a spec, review it, and create tickets.\n\n{raw_meeting_notes}"
    )

    # Append enriched notes back to original file if possible
    try:
        # Extract enrichment output from chat history
        enriched_msg = next((m["content"] for m in groupchat.messages if m["name"] == "Enrichment_Agent"), None)
        if enriched_msg:
            with open(input_path, 'r') as f:
                content = f.read()
            if "## Comprehensive Overview (Auto-Generated)" not in content:
                with open(input_path, 'a') as f:
                    f.write("\n\n---\n## Comprehensive Overview (Auto-Generated)\n\n")
                    f.write(enriched_msg)
    except Exception as e:
        print(f"[Warning] Could not append to original file: {e}")

    # Sync VectorDB
    sync_vectordb_to_markdown()
    
    print(f"\n✅ FDE Workflow Complete! View your plan here: {output_plan_file}")
