import autogen
import argparse
import os
import chromadb
from datetime import datetime
import agentops

# ==============================================================================
# 1. Configuration & Argument Parsing
# ==============================================================================
parser = argparse.ArgumentParser(description="AI-Powered FDE Orchestrator")
parser.add_argument("input_file", help="Path to the raw Markdown meeting notes (e.g., ~/Obsidian/meeting.md)")
args = parser.parse_args()

# Initialize AgentOps for LLM Observability
agentops.init(api_key=os.environ.get("AGENTOPS_API_KEY", "optional-fallback-key"))

# Determine Output Files
input_path = os.path.abspath(args.input_file)
base_name = os.path.splitext(os.path.basename(input_path))[0]
output_dir = os.path.dirname(input_path)
output_plan_file = os.path.join(output_dir, f"{base_name}_FDE_Plan.md")
knowledge_base_file = os.path.join(output_dir, "fde_knowledge_base.md")

# Load LLM Config
config_list = [
    {
        "model": "gemini-3.1-pro-preview",
        "api_type": "google",
        "project": os.environ.get("GOOGLE_VERTEX_PROJECT", "extreme-karma-gm"),
        "location": os.environ.get("GOOGLE_VERTEX_LOCATION", "global")
    }
]

llm_config = {
    "config_list": config_list,
    "temperature": 0.1, # Deterministic outputs
    "max_tokens": 8000, # Allow the model to write long, detailed tickets without getting cut off
    "request_timeout": 300, # Added a much longer timeout (5 minutes) for local models generating huge tickets
}

# ==============================================================================
# 2. Hybrid Memory System (ChromaDB + Markdown)
# ==============================================================================
print("Initializing ChromaDB Semantic Memory...")
db_client = chromadb.PersistentClient(path="./chroma_fde_memory")
collection = db_client.get_or_create_collection(name="fde_rules")

def sync_vectordb_to_markdown():
    """Extracts all learned rules from ChromaDB and writes them to a visible Markdown file."""
    try:
        rules = collection.get()
        if rules and rules['documents']:
            with open(knowledge_base_file, 'w') as f:
                f.write("# FDE AI Knowledge Base & Learned Rules\n\n")
                f.write("> *This file is auto-generated by the FDE Orchestrator's semantic memory. It allows human review of what the AI has learned.*\n\n")
                for doc in rules['documents']:
                    f.write(f"- {doc}\n")
    except Exception as e:
        print(f"Failed to sync VectorDB: {e}")

# Read existing rules to inject into the PM and Architect prompts
existing_rules_prompt = ""
try:
    existing_rules = collection.get()
    if existing_rules and existing_rules['documents']:
        existing_rules_prompt = "\n\nCRITICAL KNOWLEDGE BASE RULES TO FOLLOW:\n" + "\n".join([f"- {r}" for r in existing_rules['documents']])
except Exception:
    pass

# ==============================================================================
# 3. Define the Agents (Human-in-the-Loop enabled)
# ==============================================================================

# User Proxy (You).
user_proxy = autogen.UserProxyAgent(
    name="User_Proxy",
    system_message="A human FDE admin. You provide notes and approve the architecture before tickets are made.",
    human_input_mode="NEVER", # Changed to NEVER for headless automation. Change to TERMINATE to pause for manual review in terminal.
    max_consecutive_auto_reply=0,
    code_execution_config=False,
)

discovery_agent = autogen.AssistantAgent(
    name="Discovery_Agent",
    system_message=(
        "You are an expert Forward Deployed Product Manager. "
        "Take raw, messy meeting notes and extract the core business problem, "
        "user needs, and a structured list of desired features. Output a clear 'Product Spec'."
        + existing_rules_prompt
    ),
    llm_config=llm_config,
)

enrichment_agent = autogen.AssistantAgent(
    name="Enrichment_Agent",
    system_message=(
        "You are an expert FDE Note Taker and Technical Analyst. "
        "Take raw, vague meeting notes and expand them into a highly comprehensive, professional meeting overview. "
        "Extrapolate reasonable business context, identify implied stakeholders, and expand on the technical hints. "
        "Output ONLY the comprehensive markdown overview."
        + existing_rules_prompt
    ),
    llm_config=llm_config,
)

architect_agent = autogen.AssistantAgent(
    name="Architect_Agent",
    system_message=(
        "You are a Senior Systems Architect. You review Product Specs provided by the Discovery_Agent. "
        "Stress-test the architecture for edge cases, database choices, and infrastructure (Docker/K8s). "
        "Output technical constraints that must be added to the tickets."
        + existing_rules_prompt
    ),
    llm_config=llm_config,
)

ticket_agent = autogen.AssistantAgent(
    name="Ticket_Agent",
    system_message=(
        "You are a Senior Agile Delivery Manager. You take the Product Spec and constraints, "
        "and break them down into highly comprehensive Linear tickets. "
        "You MUST output the tickets in pure Markdown format. "
        "For EACH ticket, use EXACTLY this format:\n\n"
        "=== TICKET ===\n"
        "TITLE: [Insert clear ticket title]\n"
        "DESCRIPTION:\n"
        "**User Story:** As a... I want to... So that...\n\n"
        "**Technical Steps:**\n- Step 1\n- Step 2\n\n"
        "**Acceptance Criteria (Gherkin):**\nGiven... When... Then...\n\n"
        "**Blockers & Edge Cases:**\n- Blocker 1\n\n"
    ),
    llm_config=llm_config,
)

# ==============================================================================
# 4. Custom Tool: Linear Ticket Creation with Local Fallback
# ==============================================================================
def create_linear_ticket(title: str, description: str):
    """
    Simulates calling the Linear GraphQL API.
    If the API fails or is unavailable, triggers a fallback to append the ticket to the local Markdown plan.
    """
    print(f"\n[Tool Execution] Attempting to create Linear Ticket: {title}")
    
    # Simulate API Failure / Environment missing
    if not os.environ.get("LINEAR_API_KEY"):
        print("[Fallback Triggered] LINEAR_API_KEY not found. Appending ticket to local FDE Plan file instead.")
        with open(output_plan_file, "a") as f:
            f.write(f"\n### LINEAR TICKET: {title}\n")
            f.write(f"{description}\n")
            f.write("---\n")
        return f"Success (Fallback): Ticket '{title}' saved locally to {output_plan_file}."
    
    return f"Success: Ticket '{title}' created in Linear."

def parse_and_create_tickets(raw_output):
    """Parses the Markdown output and programmatically creates tickets."""
    tickets = raw_output.split('=== TICKET ===')
    for ticket_text in tickets:
        ticket_text = ticket_text.strip()
        if not ticket_text:
            continue
        
        title = "Untitled Ticket"
        description = ticket_text
        
        lines = ticket_text.split('\n')
        for i, line in enumerate(lines):
            if line.upper().startswith('TITLE:'):
                title = line[6:].strip()
                desc_body = '\n'.join(lines[i+1:]).strip()
                if desc_body.upper().startswith('DESCRIPTION:'):
                    desc_body = desc_body[12:].strip()
                description = desc_body
                break
        
        create_linear_ticket(title, description)

# ==============================================================================
# 5. Run the Workflow! (Sequential Pipeline)
# ==============================================================================
if __name__ == "__main__":
    print(f"🚀 Initiating FDE Sequential Pipeline for: {input_path}\n")
    
    # Read the input file
    try:
        with open(input_path, 'r') as f:
            raw_meeting_notes = f.read()
    except FileNotFoundError:
        print(f"Error: Could not find file {input_path}")
        exit(1)

    # Prepare output file
    with open(output_plan_file, "w") as f:
        f.write(f"# FDE Workflow Plan: {base_name}\n\n")

    # --------------------------------------------------------------------------
    # STEP 0: Note Enrichment
    # --------------------------------------------------------------------------
    print("\n--- STEP 0: Enriching Raw Notes ---")
    user_proxy.initiate_chat(
        enrichment_agent,
        message=f"Please expand these raw meeting notes into a comprehensive, professional meeting overview:\n\n{raw_meeting_notes}"
    )
    enriched_notes = user_proxy.last_message(enrichment_agent)["content"]

    # Append the enriched notes back to the original input file
    try:
        with open(input_path, 'r') as f:
            content = f.read()
        
        # Don't append multiple times if we run this on the same file over and over
        if "## Comprehensive Overview (Auto-Generated)" not in content:
            with open(input_path, 'a') as f:
                f.write("\n\n---\n## Comprehensive Overview (Auto-Generated)\n\n")
                f.write(enriched_notes)
            print(f"\n[Success] Appended Comprehensive Overview to {input_path}")
    except Exception as e:
        print(f"[Warning] Could not append to original file: {e}")

    # --------------------------------------------------------------------------
    # STEP 1: Discovery (Product Spec)
    # --------------------------------------------------------------------------
    print("\n--- STEP 1: Generating Product Spec ---")
    user_proxy.initiate_chat(
        discovery_agent,
        message=f"Please process this comprehensive meeting overview into a detailed Product Spec.\n\nOVERVIEW:\n{enriched_notes}",
        clear_history=True
    )
    product_spec = user_proxy.last_message(discovery_agent)["content"]
    
    # --------------------------------------------------------------------------
    # STEP 2: Architecture Review
    # --------------------------------------------------------------------------
    print("\n--- STEP 2: Stress-Testing Architecture ---")
    user_proxy.initiate_chat(
        architect_agent,
        message=f"Here is the Product Spec. Please review it, stress-test the architecture, and output technical constraints.\n\nSPEC:\n{product_spec}",
        clear_history=True
    )
    architecture_review = user_proxy.last_message(architect_agent)["content"]

    # --------------------------------------------------------------------------
    # STEP 3: Ticket Generation
    # --------------------------------------------------------------------------
    print("\n--- STEP 3: Generating Linear Tickets ---")
    user_proxy.initiate_chat(
        ticket_agent,
        message=f"Here is the Product Spec and Architect constraints. Please break them down into tickets.\n\nSPEC:\n{product_spec}\n\nCONSTRAINTS:\n{architecture_review}",
        clear_history=True
    )
    final_tickets = user_proxy.last_message(ticket_agent)["content"]

    # Parse and save the tickets programmatically
    try:
        with open(output_plan_file, "a") as f:
            f.write("\n\n## Generated Linear Tickets\n\n")
        
        parse_and_create_tickets(final_tickets)
        
        with open(output_plan_file, "a") as f:
            f.write("\n\n---\n*End of FDE Plan*\n")
    except Exception as e:
        print(f"[Warning] Could not append final tickets to plan file: {e}")

    # Sync VectorDB to Markdown at the end of the run
    sync_vectordb_to_markdown()
    
    print(f"\n✅ FDE Workflow Complete! View your plan here: {output_plan_file}")
